# Generated by Django 5.0.6 on 2026-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.CharField(help_text='Siglas cortas, ej: HV, HDL', max_length=10, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('hospital_publico', 'Hospital Público'), ('hospital_privado', 'Hospital Privado'), ('clinica', 'Clínica'), ('centro_acopio', 'Centro de Acopio'), ('refugio', 'Refugio'), ('proteccion_civil', 'Protección Civil'), ('cruz_roja', 'Cruz Roja'), ('otro', 'Otro')], default='hospital_publico', max_length=30, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('amazonas', 'Amazonas'), ('anzoategui', 'Anzoátegui'), ('apure', 'Apure'), ('aragua', 'Aragua'), ('barinas', 'Barinas'), ('bolivar', 'Bolívar'), ('carabobo', 'Carabobo'), ('cojedes', 'Cojedes'), ('delta_amacuro', 'Delta Amacuro'), ('dependencias_fed', 'Dependencias Federales'), ('distrito_capital', 'Distrito Capital'), ('falcon', 'Falcón'), ('guarico', 'Guárico'), ('lara', 'Lara'), ('merida', 'Mérida'), ('miranda', 'Miranda'), ('monagas', 'Monagas'), ('nueva_esparta', 'Nueva Esparta'), ('portuguesa', 'Portuguesa'), ('sucre', 'Sucre'), ('tachira', 'Táchira'), ('trujillo', 'Trujillo'), ('la_guaira', 'La Guaira (Vargas)'), ('yaracuy', 'Yaracuy'), ('zulia', 'Zulia')], max_length=30, verbose_name='Estado venezolano')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad / Municipio')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono_principal', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('capacidad_aproximada', models.IntegerField(blank=True, null=True, verbose_name='Capacidad aprox.')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Hospital / Centro',
                'verbose_name_plural': 'Hospitales / Centros',
                'ordering': ['nombre'],
            },
        ),
    ]
