# Generated by Django 5.0.6 on 2026-06-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del edificio')),
                ('estado', models.CharField(choices=[('amazonas', 'Amazonas'), ('anzoategui', 'Anzoátegui'), ('apure', 'Apure'), ('aragua', 'Aragua'), ('barinas', 'Barinas'), ('bolivar', 'Bolívar'), ('carabobo', 'Carabobo'), ('cojedes', 'Cojedes'), ('delta_amacuro', 'Delta Amacuro'), ('dependencias_fed', 'Dependencias Federales'), ('distrito_capital', 'Distrito Capital'), ('falcon', 'Falcón'), ('guarico', 'Guárico'), ('lara', 'Lara'), ('merida', 'Mérida'), ('miranda', 'Miranda'), ('monagas', 'Monagas'), ('nueva_esparta', 'Nueva Esparta'), ('portuguesa', 'Portuguesa'), ('sucre', 'Sucre'), ('tachira', 'Táchira'), ('trujillo', 'Trujillo'), ('la_guaira', 'La Guaira (Vargas)'), ('yaracuy', 'Yaracuy'), ('zulia', 'Zulia')], max_length=30, verbose_name='Estado venezolano')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad / Municipio')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('estado_estructural', models.CharField(choices=[('derrumbado', 'Derrumbado'), ('parcialmente_danado', 'Parcialmente dañado'), ('integridad_delicada', 'Integridad delicada'), ('evacuado', 'Evacuado'), ('en_evaluacion', 'En evaluación')], default='en_evaluacion', max_length=30, verbose_name='Estado estructural')),
                ('notas', models.TextField(blank=True, verbose_name='Notas / Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Edificio afectado',
                'verbose_name_plural': 'Edificios afectados',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
