# Generated by Django 5.0.6 on 2026-06-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilHospital',
        ),
    ]
