# Generated by Django 5.0.6 on 2026-06-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaReportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_caso', models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='ID Caso')),
                ('cedula', models.CharField(blank=True, help_text='Solo números, sin puntos ni prefijo V/E', max_length=10, verbose_name='Cédula')),
                ('nacionalidad_cedula', models.CharField(blank=True, choices=[('V', 'Venezolano/a (V)'), ('E', 'Extranjero/a (E)'), ('P', 'Pasaporte')], max_length=2, verbose_name='Tipo cédula')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('alias_o_apodos', models.CharField(blank=True, help_text='Separados por coma', max_length=200, verbose_name='Alias / Apodos')),
                ('edad_aproximada', models.IntegerField(blank=True, null=True, verbose_name='Edad aproximada')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('no_especifica', 'No especifica')], max_length=15, verbose_name='Sexo')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo de sangre')),
                ('estado_ultima_ubicacion', models.CharField(blank=True, choices=[('amazonas', 'Amazonas'), ('anzoategui', 'Anzoátegui'), ('apure', 'Apure'), ('aragua', 'Aragua'), ('barinas', 'Barinas'), ('bolivar', 'Bolívar'), ('carabobo', 'Carabobo'), ('cojedes', 'Cojedes'), ('delta_amacuro', 'Delta Amacuro'), ('dependencias_fed', 'Dependencias Federales'), ('distrito_capital', 'Distrito Capital'), ('falcon', 'Falcón'), ('guarico', 'Guárico'), ('lara', 'Lara'), ('merida', 'Mérida'), ('miranda', 'Miranda'), ('monagas', 'Monagas'), ('nueva_esparta', 'Nueva Esparta'), ('portuguesa', 'Portuguesa'), ('sucre', 'Sucre'), ('tachira', 'Táchira'), ('trujillo', 'Trujillo'), ('la_guaira', 'La Guaira (Vargas)'), ('yaracuy', 'Yaracuy'), ('zulia', 'Zulia')], max_length=30, verbose_name='Estado (última ubicación)')),
                ('detalle_ultima_ubicacion', models.CharField(blank=True, help_text='Sector, parroquia, referencia', max_length=200, verbose_name='Detalle ubicación')),
                ('fecha_ultimo_contacto', models.DateField(verbose_name='Fecha último contacto')),
                ('estado_actual', models.CharField(choices=[('sin_informacion', 'Sin información'), ('reportado', 'Reportado'), ('en_traslado', 'En traslado'), ('en_centro_acopio', 'En centro de acopio'), ('hospitalizado', 'Hospitalizado — Estable'), ('hospitalizado_critico', 'Hospitalizado — Crítico'), ('dado_de_alta', 'Dado de alta'), ('localizado_con_vida', 'Localizado con vida'), ('no_confirmado', 'Sin confirmar'), ('fallecido', 'Fallecido')], default='reportado', max_length=30, verbose_name='Estado actual')),
                ('hospital_origen', models.CharField(blank=True, help_text='Si fue trasladada, centro anterior', max_length=200, verbose_name='Hospital de origen')),
                ('nombre_reportante', models.CharField(max_length=200, verbose_name='Nombre reportante')),
                ('relacion_reportante', models.CharField(blank=True, max_length=100, verbose_name='Relación')),
                ('telefono_reportante', models.CharField(max_length=20, verbose_name='Teléfono reportante')),
                ('canal_reportante', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('web_chat', 'Web Chat'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('llamada', 'Llamada'), ('otro', 'Otro')], max_length=20, verbose_name='Canal')),
                ('consentimiento_datos', models.BooleanField(default=False, verbose_name='Consentimiento datos')),
                ('fuente_informacion', models.CharField(choices=[('hospital', 'Hospital'), ('proteccion_civil', 'Protección Civil'), ('cruz_roja', 'Cruz Roja'), ('centro_acopio', 'Centro de Acopio'), ('red_social_verificada', 'Red Social Verificada'), ('reporte_familiar', 'Reporte Familiar'), ('otro', 'Otro')], max_length=30, verbose_name='Fuente')),
                ('detalle_fuente', models.CharField(blank=True, max_length=200, verbose_name='Detalle fuente')),
                ('fecha_fuente', models.DateField(blank=True, null=True, verbose_name='Fecha fuente')),
                ('validado_por', models.CharField(max_length=100, verbose_name='Validado por')),
                ('caso_sensible', models.BooleanField(default=False, verbose_name='Caso sensible')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centros.hospital', verbose_name='Hospital / Centro')),
            ],
            options={
                'verbose_name': 'Persona Reportada',
                'verbose_name_plural': 'Personas Reportadas',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='FuenteActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('sin_informacion', 'Sin información'), ('reportado', 'Reportado'), ('en_traslado', 'En traslado'), ('en_centro_acopio', 'En centro de acopio'), ('hospitalizado', 'Hospitalizado — Estable'), ('hospitalizado_critico', 'Hospitalizado — Crítico'), ('dado_de_alta', 'Dado de alta'), ('localizado_con_vida', 'Localizado con vida'), ('no_confirmado', 'Sin confirmar'), ('fallecido', 'Fallecido')], max_length=30, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('sin_informacion', 'Sin información'), ('reportado', 'Reportado'), ('en_traslado', 'En traslado'), ('en_centro_acopio', 'En centro de acopio'), ('hospitalizado', 'Hospitalizado — Estable'), ('hospitalizado_critico', 'Hospitalizado — Crítico'), ('dado_de_alta', 'Dado de alta'), ('localizado_con_vida', 'Localizado con vida'), ('no_confirmado', 'Sin confirmar'), ('fallecido', 'Fallecido')], max_length=30, verbose_name='Estado nuevo')),
                ('fuente', models.CharField(choices=[('hospital', 'Hospital'), ('proteccion_civil', 'Protección Civil'), ('cruz_roja', 'Cruz Roja'), ('centro_acopio', 'Centro de Acopio'), ('red_social_verificada', 'Red Social Verificada'), ('reporte_familiar', 'Reporte Familiar'), ('otro', 'Otro')], max_length=30, verbose_name='Fuente')),
                ('detalle', models.CharField(blank=True, max_length=200, verbose_name='Detalle')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('registrado_por', models.CharField(max_length=100, verbose_name='Registrado por')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='personas.personareportada', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Actualización de Estado',
                'verbose_name_plural': 'Historial de Actualizaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
