# Generated by Django 5.0.6 on 2026-06-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personareportada',
            name='canal_reportante',
        ),
        migrations.RemoveField(
            model_name='personareportada',
            name='consentimiento_datos',
        ),
        migrations.RemoveField(
            model_name='personareportada',
            name='nombre_reportante',
        ),
        migrations.RemoveField(
            model_name='personareportada',
            name='relacion_reportante',
        ),
        migrations.RemoveField(
            model_name='personareportada',
            name='telefono_reportante',
        ),
    ]
