# Generated by Django 5.0.6 on 2026-06-26 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_remove_personareportada_canal_reportante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personareportada',
            name='fecha_ultimo_contacto',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha último contacto'),
        ),
        migrations.AlterField(
            model_name='personareportada',
            name='fuente_informacion',
            field=models.CharField(blank=True, choices=[('hospital', 'Hospital'), ('proteccion_civil', 'Protección Civil'), ('cruz_roja', 'Cruz Roja'), ('centro_acopio', 'Centro de Acopio'), ('red_social_verificada', 'Red Social Verificada'), ('reporte_familiar', 'Reporte Familiar'), ('otro', 'Otro')], max_length=30, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='personareportada',
            name='validado_por',
            field=models.CharField(blank=True, max_length=100, verbose_name='Validado por'),
        ),
    ]
