# Generated by Django 5.0.6 on 2026-06-26 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0002_edificio'),
        ('personas', '0003_alter_personareportada_fecha_ultimo_contacto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personareportada',
            name='detalle_fuente',
        ),
        migrations.RemoveField(
            model_name='personareportada',
            name='fecha_fuente',
        ),
        migrations.RemoveField(
            model_name='personareportada',
            name='fuente_informacion',
        ),
        migrations.RemoveField(
            model_name='personareportada',
            name='validado_por',
        ),
        migrations.AlterField(
            model_name='personareportada',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='centros.hospital', verbose_name='Hospital / Centro'),
        ),
        migrations.AlterField(
            model_name='personareportada',
            name='hospital_origen',
            field=models.CharField(blank=True, help_text='Hospital, refugio, sector u otro lugar donde fue visto por última vez', max_length=200, verbose_name='Última ubicación conocida'),
        ),
        migrations.CreateModel(
            name='ActualizacionEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('sin_informacion', 'Sin información'), ('reportado', 'Reportado'), ('en_traslado', 'En traslado'), ('en_centro_acopio', 'En centro de acopio'), ('hospitalizado', 'Hospitalizado — Estable'), ('hospitalizado_critico', 'Hospitalizado — Crítico'), ('dado_de_alta', 'Dado de alta'), ('localizado_con_vida', 'Localizado con vida'), ('no_confirmado', 'Sin confirmar'), ('fallecido', 'Fallecido')], max_length=30, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('sin_informacion', 'Sin información'), ('reportado', 'Reportado'), ('en_traslado', 'En traslado'), ('en_centro_acopio', 'En centro de acopio'), ('hospitalizado', 'Hospitalizado — Estable'), ('hospitalizado_critico', 'Hospitalizado — Crítico'), ('dado_de_alta', 'Dado de alta'), ('localizado_con_vida', 'Localizado con vida'), ('no_confirmado', 'Sin confirmar'), ('fallecido', 'Fallecido')], max_length=30, verbose_name='Estado nuevo')),
                ('notas', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('registrado_por', models.CharField(max_length=100, verbose_name='Registrado por')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='personas.personareportada', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Actualización de Estado',
                'verbose_name_plural': 'Historial de Actualizaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='FuenteActualizacion',
        ),
    ]
