# Generated by Django 5.0.6 on 2026-06-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_remove_personareportada_detalle_fuente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionestado',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('sin_informacion', 'Sin información'), ('reportado', 'Reportado'), ('en_traslado', 'En traslado'), ('en_centro_acopio', 'En centro de acopio'), ('en_centro_atencion', 'En centro de atención'), ('hospitalizado', 'Hospitalizado — Estable'), ('hospitalizado_critico', 'Hospitalizado — Crítico'), ('dado_de_alta', 'Dado de alta'), ('localizado_con_vida', 'Localizado con vida'), ('no_confirmado', 'Sin confirmar'), ('fallecido', 'Fallecido')], max_length=30, verbose_name='Estado anterior'),
        ),
        migrations.AlterField(
            model_name='actualizacionestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('sin_informacion', 'Sin información'), ('reportado', 'Reportado'), ('en_traslado', 'En traslado'), ('en_centro_acopio', 'En centro de acopio'), ('en_centro_atencion', 'En centro de atención'), ('hospitalizado', 'Hospitalizado — Estable'), ('hospitalizado_critico', 'Hospitalizado — Crítico'), ('dado_de_alta', 'Dado de alta'), ('localizado_con_vida', 'Localizado con vida'), ('no_confirmado', 'Sin confirmar'), ('fallecido', 'Fallecido')], max_length=30, verbose_name='Estado nuevo'),
        ),
        migrations.AlterField(
            model_name='personareportada',
            name='estado_actual',
            field=models.CharField(choices=[('sin_informacion', 'Sin información'), ('reportado', 'Reportado'), ('en_traslado', 'En traslado'), ('en_centro_acopio', 'En centro de acopio'), ('en_centro_atencion', 'En centro de atención'), ('hospitalizado', 'Hospitalizado — Estable'), ('hospitalizado_critico', 'Hospitalizado — Crítico'), ('dado_de_alta', 'Dado de alta'), ('localizado_con_vida', 'Localizado con vida'), ('no_confirmado', 'Sin confirmar'), ('fallecido', 'Fallecido')], default='reportado', max_length=30, verbose_name='Estado actual'),
        ),
    ]
